In [ ]:
import pandas as pd
import numpy as np

In [ ]:
dict={'col1': [1,2,3,np.nan],
 'col2':[4,np.nan,6,7],
 'col3':['a','b','c',None]}

In [ ]:
df = pd.DataFrame(dict)
df

   col1  col2  col3
0   1.0   4.0     a
1   2.0   NaN     b
2   3.0   6.0     c
3   NaN   7.0  None

In [ ]:
df.fillna('Missing')

      col1     col2     col3
0      1.0      4.0        a
1      2.0  Missing        b
2      3.0      6.0        c
3  Missing      7.0  Missing

In [ ]:
df.interpolate()

   col1  col2  col3
0   1.0   4.0     a
1   2.0   5.0     b
2   3.0   6.0     c
3   3.0   7.0  None

In [ ]:
df.dropna()

   col1  col2 col3
0   1.0   4.0    a
2   3.0   6.0    c